-- Run this in Supabase SQL Editor to enable persistent schema RAG for Admin SQL.
-- The API will insert/update rows after you call:
-- Invoke-RestMethod "http://127.0.0.1:8000/api/sql/schema-vector/index" -Method Post

create extension if not exists vector;

create table if not exists public.schema_chunks (
  chunk_id text primary key,
  table_name text not null,
  schema_text text not null,
  embedding vector(768) not null,
  updated_at text not null
);

alter table public.schema_chunks enable row level security;

create index if not exists schema_chunks_embedding_idx
on public.schema_chunks
using ivfflat (embedding vector_cosine_ops)
with (lists = 100);

create index if not exists schema_chunks_table_name_idx
on public.schema_chunks (table_name);

-- No seed rows are inserted here because embeddings must be generated by Ollama.
-- The app will seed these schema chunks:
-- - transfers
-- - llm_usage_logs
-- - assistant_question_logs
